main:
  - name: Home
    pageRef: /
    weight: 10
  - name: Research
    pageRef: /projects
    weight: 20
  - name: Publications
    pageRef: /publications
    weight: 30
  - name: Education & Experience
    pageRef: /experience
    weight: 40
